### ISSUE TITLE
UndefinedError: Measure is undefined if there are no relevant or retrieved items

### ISSUE THREAD

**Issue by umer7267** [rafguns/linkpred#39] opened 2023-05-11 18:41 UTC
I am getting the undefined error when plotting ROC Curve of an evaluation using the following code:

```
n = len(test)
num_universe = n * (n - 1) // 2

test_set = set(linkpred.evaluation.Pair(u, v) for u, v in test.edges())
evaluation = linkpred.evaluation.EvaluationSheet(cn_results, test_set, num_universe)
plt.plot(evaluation.fallout(), evaluation.recall())
plt.show()
```

**Comment by rafguns** [comment] 2023-06-02 18:57
Hi! Can you share the network `test`? For instance, as an edgelist or in some other networkx-compatible format?

**Comment by rafguns** [comment] 2024-11-29 12:02
Closing due to lack of information. Please reopen if you have more info on how to reproduce.

**Closed by rafguns** 2024-11-29 12:02 UTC
