### ISSUE TITLE
Error when clling linkpred in linux

### ISSUE THREAD

**Issue by YasCoMa** [rafguns/linkpred#22] opened 2019-01-28 14:48 UTC
I am trying to use it but when I call, it shows the following error:
/usr/bin/env: ‘python\r’: No such file or directory

**Comment by rafguns** [comment] 2019-01-28 16:06
Thanks for the report!

Did you install with `pip`? It seems that this is not an issue in the GitHub repo but just with the package on PyPI, caused by preparing it on Windows *sigh*. I'll look into better ways of preparing packages.

If you need it urgently, you can probably fix manually for now by finding the `linkpred` executable and fixing line endings (e.g., with `dos2unix`).

**Comment by rafguns** [comment] 2019-01-29 16:01
I cannot easily test this at the moment but I think this just needs to happen for the linkpred executable script. You should be able to locate it with `which linkpred` (I think).

**Comment by rafguns** [comment] 2019-01-29 16:08
To properly solve this, the best way is probably to [let Travis deploy to PyPI](https://docs.travis-ci.com/user/deployment/pypi/).

**Comment by YasCoMa** [comment] 2019-01-30 23:46
I did this for the executable linkpred...The python module worked but the command on terminal gives the following error:
ImportError: No module named linkpred.cli

**Comment by rafguns** [comment] 2019-01-31 12:41
Ouch, sorry about the trouble! I'll get my hands on a Linux box and figure out what the problem is.

**Comment by rafguns** [comment] 2019-01-31 13:20
As far as I can see, the problem may arise if multiple Python versions (or environments) are installed. I encounter this on Ubuntu when linkpred is installed using Python3/pip3, but `#!/usr/bin/env python` resolves to Python 2.7. Changing it to `#!/usr/bin/env python3`  solves the problem for my case but would cause problems for someone who installed linkpred in Python 2...

The best way to solve all this, including the original problem, is probably to start using the [`console_scripts` entry point](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point). I will work on that soon, unless someone else wnats to take a crack at it first. If so, please comment here.

**Comment by rafguns** [comment] 2019-02-05 15:47
Fixed in ce33b09.

**Comment by rafguns** [comment] 2019-02-05 15:51
I just released version 0.4, which contains the fix.

@YasCoMa Can you verify that this works on your end? You should be able to upgrade by running
```bash
pip install --upgrade linkpred
```
Thanks!

**Comment by rafguns** [comment] 2019-02-19 10:13
As far as I can tell, this is fixed. Feel free to reopen if this still pops up.

**Closed by rafguns** 2019-02-19 10:13 UTC
